### ISSUE TITLE
Quadratic terms

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterfaceUtilities.jl#12]
I started implementing support for quadratic expressions in JuMP and saw that MOIU only supports affine objectives. What is needed to support quadratic objectives?

**Comment by blegat** [comment]
We need to decide how to do it. Currently we have a field
```julia
objective::MathOptInterface.ScalarAffineFunction{T}
```

One option would be to simply replace it with
```julia
objective::MathOptInterface.AbstractScalarFunction{T}
```
The downside is that it is not a concrete type.

Another option is to add the type of the objective to the instance macro. JuMP would sets `ScalarQuadraticFunction` and when setting the objective of the solver, it should check whether there is any quadratic term and use only the scalar terms otherwise.
Not that the first option is equivalent to the second one where we give `AbstractScalarFunction` as an argument to the instance macro.

What do you think ? What's best ?

**Comment by mlubin** [comment]
I'd prefer to go with `AbstractScalarFunction`. JuMP eventually needs to allow arbitrary MOI objective functions, so using `ScalarQuadraticFunction` for everything won't work.

**Comment by mlubin** [comment]
Or you can make it a `Union{ScalarAffineFunction,ScalarQuadraticFunction}` so that dispatch is fast.
