### ISSUE TITLE
InstanceManager

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterfaceUtilities.jl#32]
So far we've been imagining that JuMP would be responsible for keeping the instance and the solver instance in sync, e.g.:
https://github.com/JuliaOpt/JuMP.jl/blob/d3e40d9a047c2da3b9242d57fb55dec1fba9301d/src/quadexpr.jl#L154
https://github.com/JuliaOpt/JuMP.jl/issues/1069

I propose to change the design a bit, and move the syncing logic to the MOI level. Let's imagine we have an `InstanceManager` that stores a standalone instance and optionally a solver instance. It would implement a variant of the MOI interface with well-defined semantics for when the solver instance is kept in sync with the standalone instance. This would be:
- easier to test as an MOI-level object rather than as part of JuMP.
- usable directly without JuMP (which I believe addresses @IssamT's comments in https://github.com/JuliaOpt/MathOptInterface.jl/issues/106)

One point that's not clear (which we'd need to resolve anyway) is whether to query the standalone instance or the solver instance for certain attributes. This comes up also in bridges: https://github.com/JuliaOpt/MathOptInterface.jl/pull/169.

@odow

**Comment by odow** [comment]
I'm in favour of JuMP having two modes:

A solver instance mode:
```julia
m = Model(GurobiInstance())
@variable(m, x)               # adds variable directly to gurobi
@constraint(m, 2x <= 10) # adds constraint directly to Gurobi. Doesn't store extra copy
solve(m)
@constraint(m, x in SomeFancySet() # errors
# Gurobi doesn't support adding a SomeFancySet constraint to a solved model.
JuMP.detach(m) # errors. This is a solver instance
```

A managed instance mode:
```julia
m = Model()
@variable(m, x)              
@constraint(m, 2x <= 10)
solve(m)  # errors.No solver instance attached
JuMP.attach(m, GurobiInstance())
@constraint(m, 2x <= 8) # immediately adds to standalone and solver instance
solve(m)  # success!
@constraint(m, x in SomeFancySet() # errors
# Gurobi doesn't support adding a SomeFancySet constraint to a solved model.

JuMP.detach(m)
@constraint(m, x in SomeFancySet() # adds constraint to standalone instance
JuMP.attach(m, GurobiInstance())
solve(m) # success!
```

I don't mind if this logic is in JuMP or in an instance manager. However it should have the following rules:

1. If a solver instance is attached to a standalone instance, changes (additions, deletions, modifications) should always be immediately reflected in both instances.

2. If a change is not supported by the standalone instance, throw an error saying that the standalone instance does not support it _regardless_ of whether the solver instance supports it.

3. If a change is supported by the standalone instance, but not by the solver instance, throw an error and ask the user to detach the solver instance, and attach a solver instance that supports the change. This might be a different solver instance if the it doesn't support the type of constraint, or the same solver instance if it doesn't support modifying the problem after solve (for example).

4. The user should query the instance manager for attributes. The manager first attempts to query the standalone instance, and if `canget` is false, queries the solver instance.

5. Users can override this behaviour by accessing the solver instance or standalone instance:
`MOI.get(MOI.SolverInstance(m), Gurobi.Attribute(), value)`

**Comment by mlubin** [comment]
I basically agree with all of those points. I think this code should be written at the MOI(U) level and mostly separate from JuMP.

**Comment by joaquimg** [comment]
I agree that having instances in sync is very good.

I noticed that in both cases we are basically adding constraints one by one. Solvers usually are much faster adding batches than one by one.

One way to have them added in batches is attaching the solver instance only after the problem is completely built in the standalone intance.

On the other hand building the batches in julia might create an overhead so that (julia creating batches+adding by batch to solve) might take longer than (adding to solver one by one).

**Comment by mlubin** [comment]
> I noticed that in both cases we are basically adding constraints one by one. Solvers usually are much faster adding batches than one by one.

`JuMP.attach` can (and should) add constraints in batches to the solver instance.

**Comment by blegat** [comment]
I like the idea of implementing an InstanceManager outside of JuMP. Defining this outside of JuMP will help make this concept clearer and more transparent to the user. It will also be helpful for package using MOI directly (e.g. I will probably use it in [this package](https://github.com/blegat/SwitchOnSafety.jl)).

**Comment by blegat** [comment]
I have been thinking about it. We could have an InstanceManager like this
```julia
struct InstanceManager <: AbstractSolverInstance
    instance::Union{Void, AbstractStandaloneInstance}
    instancesynced::Bool
    solverinstance::Union{Void, AbstractSolverInstance}
    solverinstancesynced::Bool
end
```
In addition to implementing the `AbstractSolverInstance` interface, it can do `attachsolverinstance!(instancemanager, solverinstance)`, `detachsolverinstance!(instancemanager)`, `attachinstance!(instancemanager, solverinstance)` and `detachinstance!(instancemanager)`.
When `instancesynced` is true that means that the model contained in `instance` is up to date, When `solverinstancesynced` is true that means that the model contained in `solverinstance` is up to date.

Here are the rules I suggest:
1) The manager only applies the operation to the instance whose `synced` flag is true (hence when both are up to date, the manager tries to mirror every operation to both instances).
2) Whenever one does not support a modification operation (e.g. `set!`, `add...`, ...), it sets the `synced` flag to `false` hence the manager stop applying the operations to it.
3) When `attach...` is called and the other instance is not empty then the `synced` flag is set to `false` hence the operations are not mirrored to it.
4) When only one is up to date and it does not support an operation, `copy!` is called and the other one gets is flag set to true then the operation is applied to it and the flag of the first one is set to false if that operation modifies the model (`optimize!` can be seen as a particular case of it, it does not modify the model so `instancesynced` is not set to false).

What do you think ?

**Comment by mlubin** [comment]
This object has 2^4 possible states for the combinations of instance loaded/not loaded and synced/not synced. There's even more if the behavior differs depending on whether the instances are empty or nonempty.

I was imagining that it *always* has a standalone instance loaded and synced, and may or may not have a solver instance loaded. If it has a solver instance loaded, then the solver instance is always synced. So that gives us only two possible states. If a user tries to do something that the solver instance doesn't support, they have to explicitly detach the solver instance to proceed. Calling `copy!` at times that the user can't predict defeats the intention of https://github.com/JuliaOpt/JuMP.jl/issues/1069.

**Comment by blegat** [comment]
Suppose the user has this function
```julia
function solvestuff(solver)
    m = Model()
    attach(m, solver)
    ... # sets variables and constraints
    solve(m)
    ... # modifies problem
    solve(m)
end
```
The user has no idea what the solver support and does not support and he wants JuMP to handle these technical details automatically in the most efficient way the solver allows it.
The fact that the problem first need to be stored in the instance then copied to SCS at the solve and then (say) it can be modified directly to SCS because it is just a change to the RHS does not matter here.
Having something flexible does not mean that it should be completely manual.

**Comment by mlubin** [comment]
The conclusion in https://github.com/JuliaOpt/JuMP.jl/issues/1069 was to have an option in JuMP to ignore, warn, or error when the solver doesn't support something. I still agree with this conclusion, but maybe we should draw the line between what happens in MOIU and what happens in JuMP here. I'm not sure.

**Comment by odow** [comment]
I maintain my [comment](https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/32#issuecomment-346688634) re the instance manager. JuMP can do something a bit nicer for users. But I'm in favour of it retaining the same rules

**Comment by blegat** [comment]
Here is an (hopefully) improved proposal:
```julia
struct InstanceManager <: AbstractSolverInstance
    instance::AbstractStandaloneInstance
    instancesynced::Bool
    solverinstance::Union{Void, AbstractSolverInstance}
    solverinstancesynced::Bool
end
```
There is only 8 different states now but in fact only 4 can occur and the user can know and control precisely in which states if he knows the following:
The `instance` supports all non-solver operations (where the meaning of "non-solvers" is the same as with the bridge mechanism) (if it really does not support one, throw an error as already pointed out by @odow's law 2.) hence it is always synced except manually asked not to be synced (i.e. to enter @odow 's first mode).
Here are the 4 states:
1) `instancesynced` is `true`, `solverinstance` is `Void`, `solverinstancesynced` is `false` : Instance only
2) `instancesynced` is `true`, `solverinstance` is not `Void`, `solverinstancesynced` is `false` : Solver waiting, this mode is needed if we want to allow solvers to only support `copy!`. If we want solvers
3) `instancesynced` is `true`, `solverinstance` is not `Void`, `solverinstancesynced` is `true` : Mirror, @odow second mode
4) `instancesynced` is `false`, `solverinstance` is not `Void`, `solverinstancesynced` is `true` : Solver only, @odow first mode

Here are the transitions:
* `attach(instancemanager, solverinstance)`: 1,2,3) goes in state 2). 4) Stays in same state.
* `syncsolver(instancemanager)` : 1) Error (or no-op ?). 2) goes in state 3). 3,4) stays in same state.
* `MOI.optimize!(instancemanager)`: calls `syncsolver(instancemanager)` and then do `MOI.optimize!(instancemanager.solverinstance).
* operation not supported by solver which modifies the model: 1,2) NA. 3,4) goes in state 2). Note that this transition from 3,4) to 2) is the only magic operation not specifically asked by the user and dependent on the solver. IMHO it is a good thing since this allows the user to write solver independent code and this the part of JuliaOpt where MOI.canget and MOI.canset! will show all their potential.
* `dropstandaloneinstance(instancemanager)`, 1) Error. 2,3) sets `instancesynced` to `false`, calls `empty!(instance)` and goes in state 4). 4) stays in same state.

@odow laws 1.and 3. are violated but it is not feasible if we allow solvers to only support `copy!`.
@odow laws 4. and 5. still hold.

What do you think ?

**Comment by odow** [comment]
I'm a fan of simplicity. The rules outlined in my comment seem like the simplest consistent set. I don't have a problem with forcing users to attach and detach solver instances. 

Consider the old behaviour 
```julia
m = Model()
solve(m)
``` 
that would automatically choose a solver based on whatever it could find. That seems very cool to start with, but unnecessarily obscures information from the user that ultimately leads to more issues (see https://github.com/JuliaOpt/MathProgBase.jl/pull/150#issuecomment-271464011).

How many users are aware that JuMP maintains two copies of all the data? This standalone instance and solver instance feels like a similar story with the magical solver. I like things that are explicit (but still convenient).

Is it really hard for a developer writing a higher-level toolbox to write
```julia
function solvestuff(solver)
    m = Model()
    attach(m, solver)
    ... # sets variables and constraints
    solve(m)

    if canaddconstraint(m, x<=1)
        @constraint(m, x<=1)
    else
        JuMP.detach(m)
        @constraint(m, x<=1)
        JuMP.attach(m, solver)
    end
    solve(m)
end
```

**Comment by mlubin** [comment]
@blegat, I think this can be further simplified.

> instancesynced is false, solverinstance is not Void, solverinstancesynced is true : Solver only

I don't immediately see a good reason to use an `InstanceManager` for solver-only mode when you could just use the the solver instance directly. So `InstanceManager` does not need to support this case.

Writing up more thoughts now.

**Comment by mlubin** [comment]
Here's a proposal:

Three states:
- State 1: A standalone instance only. No solver instance loaded.
- State 2: A solver instance is loaded but is empty. Not synced with the standalone instance.
- State 3: The solver instance and the standalone instance are synchronized.

Two modes of operation:
- Mode 1: When in state 3, error if cannot propagate a change to the solver instance.
- Mode 2: When in state 3, drop to state 2 if cannot propagate a change to the solver instance.

Important behavior:
- `setsolver(solverinstance)`: transition from state 1 to state 2 or from state 2 to state 2. `solverinstance` must be empty. Error if called when in state 3.
- `attachsolver()`: transition from state 2 to state 3 by calling `copy!`. `setsolver()` must be called first. (Could be relaxed to transition from state 1 to state 3 for convenience.)
- `detachsolver()`: transition from state 3 to state 2 by calling `empty!()`.
- `optimize!()`: If in state 2, call `attachsolver()`. Once in state 3, call `optimize!` on the solver instance.
- Unsupported problem modifications when in state 3: If in mode 1, throw an error. If in mode 2, call `detachsolver()` then proceed.
- Immediate error when the standalone instance does not support something. The standalone instance must always be up to date.

Mode 1 meets all of @odow's requirements. Mode 2 is a bit more user friendly and doesn't force you to detach all the time. I'd probably want to make mode 2 the default in JuMP but make it very clear that mode 1 is the way to go for experts.

**Comment by blegat** [comment]
I like the two modes approach.

Removing state 4 simplifies the `InstanceManager` indeed, we can probably add an option in JuMP to use an unmanaged solver instance like `Model(solver=() -> MosekInstance(), managed=false)` to avoid having two copies of the problem. In this case, JuMP will have a `MosekInstance` directly instead of an `InstanceManager`. When the user complains about JuMP consuming too much RAM, we'll simply suggest him to set `managed=false`. When changing the JuMP solver in `managed=false` JuMP mode, JuMP will copy the model using the `copy!` operation and replace `Mosek` with the new solver. However, JuMP will need to keep the dictionary of indices and make the translations himself. This seems a bit worrying since the job of keeping dictionaries of indices and making these things transparent seems to be the job of the `InstanceManager`.

**Comment by mlubin** [comment]
> Model(solver=() -> MosekInstance(), managed=false)

JuMP needs exactly one solver instance in the ~non-managed~ direct-solver-mode case, so there's no need for a lambda.

> When changing the JuMP solver in managed=false JuMP mode, JuMP will copy the model using the copy! operation and replace Mosek with the new solver. However, JuMP will need to keep the dictionary of indices and make the translations himself. 

There's no need to support changing solvers when JuMP is in ~unmanaged~ direct solver mode. This is morally equivalent, e.g., to using the Gurobi API directly, and users don't expect to be able to change a Gurobi API model into a CPLEX API model. What we can do is implement `copy!(::JuMP.Model, ::JuMP.Model)` analogous to `MOI.copy!` that returns a dictionary-like object that users can use to map variables and constraints across the models.

**Comment by blegat** [comment]
Ok that would work. I agree with the proposal https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/32#issuecomment-351280545.

**Comment by mlubin** [comment]
Another thing, it seems like we're converging to using empty solver instances as a way to specify the solver. Does this mean we don't need to do `() -> SolverInstance()` anywhere? That would be nice.

**Comment by blegat** [comment]
It does not seem to be needed for JuMP. I would do `@assert isempty(solverinstance)` in JuMP everytime a user provide an instance though (or at least throw a warning). It still seems to be needed in MOIT though (although we might do `empty!` at the beginning of each test instead).

**Comment by mlubin** [comment]
If we do `empty!` in MOIT it will force the solvers to implement the behavior that will be needed for JuMP anyway.

**Comment by mlubin** [comment]
InstanceManager was merged in
